version: '3.8'

services:
  backend:
    build: .
    container_name: crony-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: crony-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
